import { Entreprise, Contact, Opportunite, Interaction } from '../types/crm.types';

const KEYS = {
  entreprises: 'alpha_rh_crm_entreprises',
  contacts: 'alpha_rh_crm_contacts',
  opportunites: 'alpha_rh_crm_opportunites',
  interactions: 'alpha_rh_crm_interactions',
};

export const mockEntreprises: Entreprise[] = [
  {
    id: 'e1',
    raison_sociale: 'Tunisie Télécom',
    secteur_activite: 'Télécommunications',
    taille_entreprise: '> 500 employés',
    adresse: 'Avenue Habib Bourguiba',
    ville: 'Tunis',
    pays: 'Tunisie',
    site_web: 'www.tunisietelecom.tn',
    statut_compte: 'client',
    source_acquisition: 'Réseau professionnel',
    responsable_compte: 'Sonia Mansouri',
    remarques: 'Compte stratégique. Forte demande en soft skills et leadership.',
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-03-10').toISOString(),
  },
  {
    id: 'e2',
    raison_sociale: 'STEG',
    secteur_activite: 'Énergie',
    taille_entreprise: '> 500 employés',
    adresse: 'Rue Jemaa Essiaf',
    ville: 'Tunis',
    pays: 'Tunisie',
    site_web: 'www.steg.com.tn',
    statut_compte: 'client',
    source_acquisition: 'Appel d\'offres',
    responsable_compte: 'Karim Jebali',
    remarques: 'Cycles de formation en sécurité et HSE.',
    created_at: new Date('2024-02-01').toISOString(),
    updated_at: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'e3',
    raison_sociale: 'Groupe Mabrouk',
    secteur_activite: 'Distribution / Retail',
    taille_entreprise: '100-500 employés',
    adresse: 'Route de la Marsa',
    ville: 'La Marsa',
    pays: 'Tunisie',
    site_web: 'www.groupemabrouk.com',
    statut_compte: 'prospect',
    source_acquisition: 'Salon professionnel',
    responsable_compte: 'Sonia Mansouri',
    remarques: 'Intérêt pour formations en management et digital marketing.',
    created_at: new Date('2024-03-05').toISOString(),
    updated_at: new Date('2024-03-05').toISOString(),
  },
  {
    id: 'e4',
    raison_sociale: 'Banque de l\'Habitat',
    secteur_activite: 'Banque / Finance',
    taille_entreprise: '100-500 employés',
    adresse: 'Avenue Kheireddine Pacha',
    ville: 'Tunis',
    pays: 'Tunisie',
    site_web: 'www.bh.com.tn',
    statut_compte: 'prospect',
    source_acquisition: 'Recommandation client',
    responsable_compte: 'Karim Jebali',
    remarques: 'A contacté suite à recommandation de Tunisie Télécom.',
    created_at: new Date('2024-03-20').toISOString(),
    updated_at: new Date('2024-03-20').toISOString(),
  },
  {
    id: 'e5',
    raison_sociale: 'Poulina Group Holding',
    secteur_activite: 'Agroalimentaire',
    taille_entreprise: '> 500 employés',
    adresse: 'Les Berges du Lac',
    ville: 'Tunis',
    pays: 'Tunisie',
    site_web: 'www.poulina.tn',
    statut_compte: 'inactif',
    source_acquisition: 'Prospection directe',
    responsable_compte: 'Sonia Mansouri',
    remarques: 'Contrat terminé en 2023. À relancer pour 2024.',
    created_at: new Date('2023-06-01').toISOString(),
    updated_at: new Date('2023-12-31').toISOString(),
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'c1',
    entreprise_id: 'e1',
    nom: 'Ferchichi',
    prenom: 'Nadia',
    fonction: 'DRH',
    email: 'n.ferchichi@tunisietelecom.tn',
    telephone: '71 800 200',
    whatsapp: '98 111 222',
    role_decisionnel: 'Décideur principal',
    prefere_par: 'Email',
    remarques: 'Prend toutes les décisions de formation. Très réactive.',
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'c2',
    entreprise_id: 'e1',
    nom: 'Zouari',
    prenom: 'Mehdi',
    fonction: 'Responsable Formation',
    email: 'm.zouari@tunisietelecom.tn',
    telephone: '71 800 201',
    whatsapp: '22 333 444',
    role_decisionnel: 'Influenceur',
    prefere_par: 'WhatsApp',
    remarques: 'Gère le plan de formation annuel.',
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'c3',
    entreprise_id: 'e2',
    nom: 'Bouzid',
    prenom: 'Hatem',
    fonction: 'Directeur des Ressources Humaines',
    email: 'h.bouzid@steg.com.tn',
    telephone: '71 340 000',
    whatsapp: '55 123 456',
    role_decisionnel: 'Décideur principal',
    prefere_par: 'Téléphone',
    remarques: 'Préfère les échanges directs.',
    created_at: new Date('2024-02-01').toISOString(),
    updated_at: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'c4',
    entreprise_id: 'e3',
    nom: 'Ben Salah',
    prenom: 'Yasmine',
    fonction: 'Responsable RH',
    email: 'y.bensalah@mabrouk.tn',
    telephone: '71 700 500',
    whatsapp: '26 789 012',
    role_decisionnel: 'Contact opérationnel',
    prefere_par: 'Email',
    remarques: 'Nouvelle recrue. Enthousiaste pour les formations.',
    created_at: new Date('2024-03-05').toISOString(),
    updated_at: new Date('2024-03-05').toISOString(),
  },
  {
    id: 'c5',
    entreprise_id: 'e4',
    nom: 'Hattab',
    prenom: 'Riadh',
    fonction: 'DRH Adjoint',
    email: 'r.hattab@bh.com.tn',
    telephone: '71 127 000',
    whatsapp: '92 456 789',
    role_decisionnel: 'Influenceur',
    prefere_par: 'WhatsApp',
    remarques: 'Contact via réseau LinkedIn.',
    created_at: new Date('2024-03-20').toISOString(),
    updated_at: new Date('2024-03-20').toISOString(),
  },
];

export const mockOpportunites: Opportunite[] = [
  {
    id: 'o1',
    entreprise_id: 'e1',
    contact_id: 'c1',
    type_opportunite: 'intra',
    theme_programme: 'Leadership et Management d\'équipe',
    domaine_formation: 'Management',
    besoin_detaille: 'Formation pour les managers intermédiaires sur les compétences de leadership et la gestion des conflits.',
    nombre_participants: 20,
    budget_estime: 12000,
    date_prevue: '2024-05-15',
    etape_pipeline: 'proposition',
    probabilite: 70,
    montant_estime: 12000,
    prochaine_action: 'Envoyer la proposition commerciale définitive',
    date_prochaine_action: '2024-04-20',
    responsable_commercial: 'Sonia Mansouri',
    statut_opportunite: 'ouverte',
    created_at: new Date('2024-03-01').toISOString(),
    updated_at: new Date('2024-04-01').toISOString(),
  },
  {
    id: 'o2',
    entreprise_id: 'e2',
    contact_id: 'c3',
    type_opportunite: 'intra',
    theme_programme: 'Sécurité au Travail et HSE',
    domaine_formation: 'HSE / Sécurité',
    besoin_detaille: 'Formations obligatoires HSE pour les techniciens terrain. Certification requise.',
    nombre_participants: 45,
    budget_estime: 25000,
    date_prevue: '2024-06-01',
    etape_pipeline: 'negociation',
    probabilite: 85,
    montant_estime: 22000,
    prochaine_action: 'Réunion de négociation contractuelle',
    date_prochaine_action: '2024-04-18',
    responsable_commercial: 'Karim Jebali',
    statut_opportunite: 'ouverte',
    created_at: new Date('2024-02-10').toISOString(),
    updated_at: new Date('2024-04-05').toISOString(),
  },
  {
    id: 'o3',
    entreprise_id: 'e3',
    contact_id: 'c4',
    type_opportunite: 'sur_mesure',
    theme_programme: 'Marketing Digital et Réseaux Sociaux',
    domaine_formation: 'Marketing / Digital',
    besoin_detaille: 'Programme sur mesure pour digitaliser les équipes commerciales.',
    nombre_participants: 12,
    budget_estime: 6000,
    date_prevue: '2024-07-01',
    etape_pipeline: 'qualification',
    probabilite: 40,
    montant_estime: 6000,
    prochaine_action: 'Analyse du besoin approfondie',
    date_prochaine_action: '2024-04-25',
    responsable_commercial: 'Sonia Mansouri',
    statut_opportunite: 'ouverte',
    created_at: new Date('2024-03-15').toISOString(),
    updated_at: new Date('2024-03-15').toISOString(),
  },
  {
    id: 'o4',
    entreprise_id: 'e4',
    contact_id: 'c5',
    type_opportunite: 'inter',
    theme_programme: 'Audit Interne et Contrôle de Gestion',
    domaine_formation: 'Finance / Audit',
    besoin_detaille: 'Cycle inter-entreprises sur l\'audit interne bancaire.',
    nombre_participants: 8,
    budget_estime: 4800,
    date_prevue: '2024-09-10',
    etape_pipeline: 'prospection',
    probabilite: 20,
    montant_estime: 4800,
    prochaine_action: 'Premier appel de découverte',
    date_prochaine_action: '2024-04-22',
    responsable_commercial: 'Karim Jebali',
    statut_opportunite: 'ouverte',
    created_at: new Date('2024-03-25').toISOString(),
    updated_at: new Date('2024-03-25').toISOString(),
  },
  {
    id: 'o5',
    entreprise_id: 'e1',
    contact_id: 'c2',
    type_opportunite: 'intra',
    theme_programme: 'Communication et Prise de Parole en Public',
    domaine_formation: 'Soft Skills',
    besoin_detaille: 'Formation soft skills pour les équipes techniques.',
    nombre_participants: 30,
    budget_estime: 9000,
    date_prevue: '2024-04-30',
    etape_pipeline: 'gagnee',
    probabilite: 100,
    montant_estime: 8500,
    prochaine_action: 'Planification des sessions',
    date_prochaine_action: '2024-04-16',
    responsable_commercial: 'Sonia Mansouri',
    statut_opportunite: 'gagnee',
    created_at: new Date('2024-01-20').toISOString(),
    updated_at: new Date('2024-04-10').toISOString(),
  },
];

export const mockInteractions: Interaction[] = [
  {
    id: 'i1',
    entreprise_id: 'e1',
    contact_id: 'c1',
    opportunite_id: 'o1',
    type_interaction: 'reunion',
    objet: 'Réunion de cadrage – Besoins leadership',
    compte_rendu: 'Réunion productive. Nadia confirme le besoin pour 20 managers. Budget validé jusqu\'à 12 000 DT. Elle attend la proposition finale.',
    date_interaction: new Date('2024-04-01').toISOString(),
    utilisateur: 'Sonia Mansouri',
    prochaine_relance: new Date('2024-04-20').toISOString(),
    statut_relance: 'a_faire',
    created_at: new Date('2024-04-01').toISOString(),
    updated_at: new Date('2024-04-01').toISOString(),
  },
  {
    id: 'i2',
    entreprise_id: 'e2',
    contact_id: 'c3',
    opportunite_id: 'o2',
    type_interaction: 'appel',
    objet: 'Appel de suivi – Négociation STEG',
    compte_rendu: 'Hatem souhaite réduire le tarif à 20 000 DT. Discuté possibilité de réduire le nombre de jours. Réunion planifiée.',
    date_interaction: new Date('2024-04-05').toISOString(),
    utilisateur: 'Karim Jebali',
    prochaine_relance: new Date('2024-04-18').toISOString(),
    statut_relance: 'a_faire',
    created_at: new Date('2024-04-05').toISOString(),
    updated_at: new Date('2024-04-05').toISOString(),
  },
  {
    id: 'i3',
    entreprise_id: 'e3',
    contact_id: 'c4',
    opportunite_id: 'o3',
    type_interaction: 'email',
    objet: 'Envoi brochure programme marketing digital',
    compte_rendu: 'Brochure et catalogue envoyés. Yasmine a confirmé réception. En attente de son retour avec les détails du besoin.',
    date_interaction: new Date('2024-03-20').toISOString(),
    utilisateur: 'Sonia Mansouri',
    prochaine_relance: new Date('2024-04-25').toISOString(),
    statut_relance: 'a_faire',
    created_at: new Date('2024-03-20').toISOString(),
    updated_at: new Date('2024-03-20').toISOString(),
  },
  {
    id: 'i4',
    entreprise_id: 'e1',
    contact_id: 'c2',
    opportunite_id: 'o5',
    type_interaction: 'whatsapp',
    objet: 'Confirmation contrat Soft Skills',
    compte_rendu: 'Mehdi confirme via WhatsApp la signature du bon de commande. Démarrage prévu le 30 avril.',
    date_interaction: new Date('2024-04-10').toISOString(),
    utilisateur: 'Sonia Mansouri',
    prochaine_relance: new Date('2024-04-16').toISOString(),
    statut_relance: 'effectuee',
    created_at: new Date('2024-04-10').toISOString(),
    updated_at: new Date('2024-04-10').toISOString(),
  },
  {
    id: 'i5',
    entreprise_id: 'e4',
    contact_id: 'c5',
    opportunite_id: 'o4',
    type_interaction: 'note',
    objet: 'Note interne – Banque de l\'Habitat',
    compte_rendu: 'Contact froid pour l\'instant. Riadh intéressé mais en attente du budget 2024. Relancer en mai.',
    date_interaction: new Date('2024-03-25').toISOString(),
    utilisateur: 'Karim Jebali',
    prochaine_relance: new Date('2024-05-05').toISOString(),
    statut_relance: 'a_faire',
    created_at: new Date('2024-03-25').toISOString(),
    updated_at: new Date('2024-03-25').toISOString(),
  },
];

export const seedCrmDatabase = (): void => {
  if (!localStorage.getItem(KEYS.entreprises)) {
    localStorage.setItem(KEYS.entreprises, JSON.stringify(mockEntreprises));
  }
  if (!localStorage.getItem(KEYS.contacts)) {
    localStorage.setItem(KEYS.contacts, JSON.stringify(mockContacts));
  }
  if (!localStorage.getItem(KEYS.opportunites)) {
    localStorage.setItem(KEYS.opportunites, JSON.stringify(mockOpportunites));
  }
  if (!localStorage.getItem(KEYS.interactions)) {
    localStorage.setItem(KEYS.interactions, JSON.stringify(mockInteractions));
  }
};
